# Generated by Django 2.2.24 on 2025-06-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemon_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта нахождения покемона')),
                ('longetude', models.FloatField(verbose_name='Долгота нахождения покемона')),
            ],
        ),
    ]
