# Generated by Django 2.2.24 on 2025-07-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20250624_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='desctiption',
            field=models.TextField(blank=True, null=True, verbose_name='Описание покемона'),
        ),
    ]
