# Generated by Django 2.2.24 on 2025-07-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemon_desctiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='desctiption',
            new_name='description',
        ),
    ]
