# Generated by Django 2.2.24 on 2025-07-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20250706_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_eng',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название покемона на английском'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название покемона на японском'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название покемона'),
        ),
    ]
